### ISSUE TITLE
Upgraded to latest 0.9.1 getting 404 not found

### ISSUE THREAD

**Issue by nodesocket** [kubetail-org/kubetail#161]
Just upgraded to the latest Helm chart `0.9.1` but now getting:

```
404 page not found
```

when attempting to hit my ingress. Here is my full `values.yaml`:

```yaml
kubetail:
  server:
    container:
      resources:
        requests:
          cpu: 250m
          memory: 64Mi
        limits:
          cpu: 1
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.tls.certresolver: le
      rules:
      - host: kubetail.mydomain.com
        http:
          paths:
          - path: /
            pathType: Prefix
      tls:
      - hosts:
        - kubetail.mydomain.com
        secretName: kubetail-cert
  agent:
    container:
      resources:
        requests:
          cpu: 250m
          memory: 32Mi
        limits:
          cpu: 1
```

**Comment by amorey** [comment]
try this for values.yaml (the "server" was split into separate "dashboard" and "cluster-api" components):
```yaml
kubetail:
  dashboard:
    container:
      resources:
        requests:
          cpu: 250m
          memory: 64Mi
        limits:
          cpu: 1
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.tls.certresolver: le
      rules:
      - host: kubetail.mydomain.com
        http:
          paths:
          - path: /
            pathType: Prefix
      tls:
      - hosts:
        - kubetail.mydomain.com
        secretName: kubetail-cert
  kubetail-api:
    container:
      resources:
        requests:
          cpu: 250m
          memory: 32Mi
        limits:
          cpu: 1
  kubetail-agent:
    container:
      resources:
        requests:
          cpu: 250m
          memory: 32Mi
        limits:
          cpu: 1
```
