### ISSUE TITLE
Add `LoadBalancer` type in `dashboard/service.yaml`

### ISSUE THREAD

**Issue by Antoineio** [kubetail-org/kubetail#194]
Hello,
I'm trying to install `kubetail` using **Helm** with the following commands:
```
helm repo add kubetail https://kubetail-org.github.io/helm-charts/
helm install kubetail kubetail/kubetail --namespace kubetail-system --create-namespace -f <path-to-my-values.yaml>
```
Below is the content of my `values.yaml` file:

```
kubetail:
  dashboard:
      image:
        registry: "docker.io"
        repository: "kubetail/kubetail-dashboard"
        tag: "0.1.9"
      service:
        name: kubetail-dashboard-service
        type: LoadBalancer
        loadBalancerIP: "<my-ip>"
  clusterAPI:
      image:  
        registry: "docker.io"
        repository: "kubetail/kubetail-cluster-api"
        tag: "0.1.4"
      service:
        name: kubetail-api-service
  clusterAgent:
      image:
        registry: "docker.io"
        repository: "kubetail/kubetail-cluster-agent"
        tag: "0.1.4"
```

I'm trying to expose the Kubetail dashboard via a `LoadBalancer` service. However, despite specifying the `type` in the values file, the service remains set to `ClusterIP`:

```
[antoine@fedora kubernetes-apps (main)]$ kubectl get svc -n kubetail-system
NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE
kubetail-api-service ClusterIP 10.43.58.214 <none> 8080/TCP 18m
kubetail-cluster-agent ClusterIP None <none> <none> 18m
kubetail-dashboard-service ClusterIP 10.43.14.53 <none> 8080/TCP 18m
```

After looking at the `dashboard/service.yaml` template on [ArtifactHub](https://artifacthub.io/packages/helm/kubetail/kubetail?modal=template&template=dashboard/service.yaml), i noticed that the service type seems hardcoded to `ClusterIP`.

Is this intentional ? Is there another recommended way to override the dashboard's service type ?

_I would like to mention that i'm relatively new to Kubernetes and Helm, so i might have missed something._
_And if this is indeed a mistake, i will be happy to work on resolving it, i see it as a good learning opportunity._

Thanks in advance for your help 😄
