### ISSUE TITLE
namespaced installation supported?

### ISSUE THREAD

**Issue by jkroepke** [kubetail-org/kubetail#21]
Hi,

I would like to ask, if kubetail supports a namespaced installation as well, e.g. auth-mode=cluster and namespaced Rolebindings only.

Thanks!

**Comment by amorey** [comment]
The helm chart doesn't currently support namespaced rolebindings but we could add it there. In addition, there's an undocumented, experimental option in the kubetail named `namespace` that restricts access to a given namespace at the UI-level. It's currently being used on the demo site (in addition to rbac under the hood): https://www.kubetail.com/demo.

Would that work for you?

Also - thanks for the helm pull request! If you're interested in adding RoleBinding support too, that would be very much appreciated otherwise I'll work on it asap.

**Comment by jkroepke** [comment]
> Also - thanks for the helm pull request! If you're interested in adding RoleBinding support too, that would be very much appreciated otherwise I'll work on it asap.

Thats something I can cover. There are also a few options missing in helm chart that I would like to add, e.g. `securityContext`,`autoMountServiceAccountToken` and or tpl support at ingress. I have already a commit in draft.

**Comment by amorey** [comment]
Sounds great! Looking forward to checking out the PR.

**Comment by jkroepke** [comment]
> Would that work for you?

I had no success here:

I'm using the image `kubetail/kubetail:0.1.9` and I have assign RoleBindings and a Role to a service account.

![image](https://github.com/kubetail-org/kubetail/assets/1560587/5f5d7e92-a047-4dee-8f8b-3018930695fb)

The logs remains empty and on browser console, there is an error visible that the serviceAccount try to access nodes (which are a cluster-scoped resource). 

Maybe there can be implement a try/catch we ignores the error, if the nodes are not available.

**Comment by amorey** [comment]
Currently you have to give it cluster-scoped access to nodes and namespaces:
```yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubetail
rules:
- apiGroups: [""]
  resources: ["nodes", "namespaces"]
  verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubetail
subjects:
- kind: ServiceAccount
  namespace: kubetail
  name: kubetail
roleRef:
  kind: ClusterRole
  name: kubetail
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: my-namespace
  name: kubetail
rules:
- apiGroups: ["", "apps", "batch"]
  resources: ["cronjobs", "daemonsets", "deployments", "jobs", "pods", "pods/log", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kubetail
  name: my-namespace
subjects:
- kind: ServiceAccount
  name: kubetail
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubetail
```

I think reworking the app so it's namespace-scoped and doesn't need cluster-scoped access to get/list/watch namespaces shouldn't be too difficult but adding an option to remove the need for nodes would take more work.

**Comment by rophy** [comment]
> ```yaml
> kind: ConfigMap
> apiVersion: v1
> metadata:
>   namespace: kubetail
>   name: kubetail
> data:
>   config.yaml: |
>     addr: :4000
>     auth-mode: cluster
>     namespace: my-namespace
> ```

Please make the namespace a list so multiple namespaces can be supported.

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: kubetail
  name: kubetail
data:
  config.yaml: |
    addr: :4000
    auth-mode: cluster
    namespaces:
    - my-namespace
```
