### ISSUE TITLE
Query Errors if BasicAuth used

### ISSUE THREAD

**Issue by SlavikCA** [kubetail-org/kubetail#327]
In the scenario when kubetail installed in the cluster and BasicAuth used - it can't communicate with the `cluster-api-proxy/graphql` endpoint.

Steps to reproduce:
- I have Harvester Kubernetes cluster, with Traefik ingress controller.
- I added secret and middleware:

```
apiVersion: v1
kind: Secret
metadata:
  name: kubetail-auth
  namespace: logs
type: Opaque
data:
  # that's user "logs" and password "logs"
  auth: bG9nczokYXByMSRtR3BrZHRZeiRPWDFnT1IwNUYwa1VEM0E3VklMWFcuCgo=
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: kubetail-auth
  namespace: logs
spec:
  basicAuth:
    secret: kubetail-auth
```

`kubectl apply -f logs/kubetail-pass.yaml`

- I deployed Helm chart with following values:

```
kubetail:
  dashboard:
    ingress:
      enabled: true
      name: kubetail
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: logs-kubetail-auth@kubernetescrd
      rules:
        - host: <MY.HOST.URL>
          http:
            paths:
              - path: /
                pathType: Prefix
      tls: []
      className: traefik
```

`helm install kubetail kubetail/kubetail --namespace logs -f logs/kubetail.yaml`

When I open <MY.HOST.URL> - it loads fine, I can see all pods, Replicas, ...
But I see error: 

```
Query Errors(1)
Dismiss All
[GraphQL Error] kubernetes://kubetail-cluster-agent:50051/: rpc error: code = Unauthenticated desc = missing token
```

And looking in network tab, I see request failing:
URL: <MY.HOST.URL>/cluster-api-proxy/graphql
Response:
```
{
    "errors": [
        {
            "message": "kubernetes://kubetail-cluster-agent:50051/: rpc error: code = Unauthenticated desc = missing token",
            "path": [
                "logMetadataList"
            ],
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            }
        },
        {
            "message": "kubernetes://kubetail-cluster-agent:50051/: rpc error: code = Unauthenticated desc = missing token",
            "path": [
                "logMetadataList"
            ],
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            }
        }
    ],
    "data": {
        "logMetadataList": null
    }
}
```

Request headers:
```
Authorization: Basic bG9nczpsb2dz
Connection: keep-alive
Content-Length: 533
Cookie: kubetail_dashhboard_csrf=MTc0NzkzMzQxNXxJbHAyVTFSeGJUVkNiamhLTjBzNVF6SlRRblp4YzJWRVZVOU9NMEpSTW5SdGNrUlZWWGhyYTBkWk9GRTlJZ289fFAqulH_Vy83qlergFrCIkoYE7zQq8Gi9GhpB3uQ5aVc
Host: ***
Origin: http://***
Referer: http://***
Sec-GPC: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36
accept: */*
apollographql-client-name: kubetail/dashboard
apollographql-client-version: 0.1.0
content-type: application/json
```

Can that be that basic auth interfere with some of graphql headers?

**Comment by SlavikCA** [comment]
I was thinking about having Traefik remove that header,
But the Traefik's dashboard shows that it removes it by default:

![Image](https://github.com/user-attachments/assets/432467b4-ac4d-4b1b-922b-e5e8139bfbf2)

So, I'm not sure what happens

**Comment by amorey** [comment]
Thanks! That's very helpful.

**Comment by SlavikCA** [comment]
As I digged more - found, that Traefik's dashboard shows `REMOVE HEADER` value incorrectly:
https://github.com/traefik/traefik/issues/11780

So, if I explicitly set:
```
spec:
  basicAuth:
    secret: kubetail-auth
    removeHeader: true
```

Then everything work, as expected.

This issue may be closed now.
