### ISSUE TITLE
Pin github actions to commit SHA

### ISSUE THREAD

**Issue by amorey** [kubetail-org/kubetail#345]
To enhance the security of our GitHub workflows we should pin actions to specific git commits:
```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Pin your action to the exact commit that you’ve audited:
      - name: Run my-audit-verified action
        uses: other-org/their-action@e4a7c3112f8a6b930cde1234567890abcdef1234
```

I think we only need to do this for actions from individual developers and we can continue to use untagged major versions for popular actions.
