### ISSUE TITLE
kubetail does not show any error when rbac is not configured correctly.

### ISSUE THREAD

**Issue by rophy** [kubetail-org/kubetail#66]
As title, running kubetail as container, with following logging config:

```yaml
logging:
  enabled: true
  level: debug
  format: pretty
  access-log:
    enabled: true
    hide-health-checks: false
```

I intentionally removed the ClusterRoleBinding, and try to access logs from frontend. 
Accessing the UI will see no error message from both backend log and UI, the UI simply shows "Beginning of feed" with no logs.

Adding the ClusterRole back and I'll see the logs. 
Ideally, I expect to see rbac errors at the backend log.
